AhkClass(WinTitle)
AhkId(WinTitle)
AhkPid(WinTitle)
AhkExe(WinTitle)
AhkGroup(WinTitle)
AutoTrim(Options = "")
BlockInput(Options = "")
Click(Options = "")
ClipWait(Timeout = "", WaitForAnyData = "")
Control(SubCommand, Value = "", Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlClick(ControlOrPos = "", WinTitle = "", WinText = "", WhichButton = "", ClickCount = "", Options = "", ExcludeTitle = "", ExcludeText = "")
ControlFocus(Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlGet(SubCommand, Value = "", Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlGetFocus(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlGetID(Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlGetPos(ByRef X, ByRef Y, ByRef Width, ByRef Height, ControlID)
ControlGetText(Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlMove(Control = "", X = "", Y = "", Width = "", Height = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlSelect(ControlID, WindowID = "")
ControlSend(Control = "", Keys = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlSendRaw(Control = "", Keys = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
ControlSetText(Control = "", NewText = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
CoordMode(TargetType, RelativeTo := "Screen")
Critical(OnOffNumeric = "On")
DetectHiddenText(OnOff)
DetectHiddenWindows(OnOff)
Drive(SubCommand = "", Value1 = "", Value2 = "")
DriveGet(SubCommand, Value = "")
DriveSpaceFree(Path)
Edit()
EditAppend(ControlID, String = "")
EditClear(ControlID)
EditGetCurrentCol(ControlID)
EditGetCurrentLine(ControlID)
EditGetLineCount(ControlID)
EditGetText(ControlID)
EditGetSelectedText(ControlID)
EditPaste(ControlID, String = "")
EditSetText(ControlID, NewText = "")
EnvAdd(ByRef Var, Value = "" , TimeUnits = "")
EnvGet(EnvVarName)
EnvSet(EnvVar, Value)
EnvSub(ByRef Var, Value = "" , TimeUnits = "")
EnvUpdate()
FileAppend(Text = "", Filename = "", Encoding = "")
FileCopy(SourcePattern = "", DestPattern = "", Overwrite = "")
FileCopyDir(Source = "", Dest = "", Overwrite = "")
FileCreateDir(DirName = "")
FileCreateShortcut(Target, ByRef LinkFile, WorkingDir = "", Args = "", Description = "", IconFile = "", ShortcutKey = "", IconNumber = "", RunState = "")
FileDelete(FilePattern = "")
FileEncoding(Encoding = "")
FileGetAttrib(Filename = "")
FileGetShortcut(LinkFile = "")
FileGetSize(Filename = "", Units = "")
FileGetTime(Filename = "", WhichTime = "")
FileGetVersion(Filename = "")
FileInstall(Source, Dest, Overwrite = "")
FileMove(SourcePattern = "", DestPattern = "", Overwrite = 0)
FileMoveDir(Source = "", Dest = "", Flag = "")
FileRead(Filename)
FileReadLine(Filename, LineNum)
FileRecycle(FilePattern = "")
FileRecycleEmpty(DriveLetter = "")
FileRemoveDir(DirName, Recurse = "")
FileRename(SourcePattern = "", DestPattern = "", Overwrite = 0)
FileSelectFile(Options = "", RootDir = "", Prompt = "", Filter = "")
FileSelectFolder(StartingFolder = "", Options = "", Prompt = "")
FileSetAttrib(Attributes = "", FilePattern = "", OperateOnFolders = "", Recurse = "")
FileSetTime(YYYYMMDDHH24MISS = "", FilePattern = "", WhichTime = "", OperateOnFolders = "", Recurse = "")
FileWrite(Text = "", Filename = "", Overwrite = 0, Encoding = "")
FormatTime(YYYYMMDDHH24MISS = "", Format = "")
GroupActivate(GroupName, Mode = "")
GroupAdd(GroupName, WindowID, Label = "")
GroupClose(GroupName, Mode = "")
GroupDeactivate(GroupName, Mode = "")
GuiControl(Subcommand = "", ControlID = "", Value = "")
GuiControlGet(Subcommand = "", ControlID = "", Param4 = "")
IfBetween(ByRef var, LowerBound, UpperBound)
IfIn(ByRef var, MatchList)
IfNotIn(ByRef var, MatchList)
IfContains(ByRef var, MatchList)
IfNotContains(ByRef var, MatchList)
ImageSearch(ByRef OutputVarX, ByRef OutputVarY, X1, Y1, X2, Y2, ImageFile)
IniDelete(Filename, Section, Key = "")
IniRead(Filename, Section, Key = "", Default = "")
IniWrite(ValueOrPairs = "", Filename = "", Section = "", Key="")
Input(Options = "", EndKeys = "", MatchList = "")
InputBox(Title = "", Prompt = "", HIDE = "", Width = "", Height = "", X = "", Y = "", Font = "", Timeout = "", Default = "")
IsBlank(var)
IsEmpty(var)
IsType(ByRef var, type)
Join(Separator, params*)
JoinPath(Dir, File)
KeyHistory()
KeyWait(KeyName, Options = "")
ListHotkeys()
ListLines(OnOff = "")
Menu(MenuName, SubCommand, Value1 = "", Value2 = "", Value3 = "", Value4 = "")
MouseClick(WhichButton = "", X = "", Y = "", ClickCount = "", Speed = "", DownOrUp = "", Relative = "")
MouseClickDrag(WhichButton, X1, Y1, X2, Y2, Speed = "", Relative = "")
MouseGetPos(ByRef OutputVarX = "", ByRef OutputVarY = "", ByRef OutputVarWin = "", ByRef OutputVarControl = "", Mode = "")
MouseMove(X, Y, Speed = "", Relative = "")
MB(Options = "", Title = "", Text = "", Timeout = "")
MsgBox(Options = "", Title = "", Text = "", Timeout = "")
OutputDebug(Text)
PixelGetColor(X, Y, RGB = "")
PixelSearch(ByRef OutputVarX, ByRef OutputVarY, X1, Y1, X2, Y2, ColorID, Variation = "", Mode = "")
PostMessage(Msg, wParam = "", lParam = "", Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
Process(SubCommand, PIDOrName = "", Value = "")
Random(Min = "", Max = "")
RegDelete(KeyName , ValueName = "")
RegRead(RootKey, SubKey, ValueName = "")
RegWrite(Valuetype = "", RootKey = "", SubKey = "", ValueName = "", Value = "")
Reload()
Run(Target = "", WorkingDir = "", Mode = "")
RunAs(User = "", Password = "", Domain = "")
RunWait(Target, WorkingDir = "", Mode = "")
Send(Keys)
SendRaw(Keys)
SendInput(Keys)
SendPlay(Keys)
SendEvent(Keys)
SendLevel(Level)
SendMessage(Msg, wParam = "", lParam = "", Control = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "", Timeout = "")
SendMode(Mode)
SetBatchLines(Value)
SetCapsLockState(State)
SetControlDelay(Delay)
SetDefaultMouseSpeed(Speed)
SetKeyDelay(Delay = "", PressDuration = "", Play = "")
SetMouseDelay(Delay, Play = "")
SetNumLockState(State)
SetRegView(RegView)
SetScrollLockState(State)
SetStoreCapsLockMode(OnOff)
SetTimer(Label = "", PeriodOnOffDelete = "", Priority = "")
SetTitleMatchMode(MatchMode = "", Speed = "")
SetWinDelayDelay(Delay)
SetWorkingDir(DirName)
Shutdown(Code)
Sleep(DelayInMilliseconds)
Sort(ByRef VarName, Options = "")
SoundBeep(Frequency = "", Duration = "")
SoundGet(ComponentType = "", ControlType = "", DeviceNumber = "")
SoundGetWaveVolume(DeviceNumber = "")
SoundPlay(Filename, Wait = "")
SoundSet(NewSetting, ComponentType = "", ControlType = "", DeviceNumber = "")
SoundSetWaveVolume(Percent , DeviceNumber = "")
SplitPath(Path = "")
StatusBarGetText(Part = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
StatusBarWait(BarText = "", Timeout = "", Part# = "", WindowID = "")
StrContains(Haystack, Needle, CaseSensitive = false, StartingPos = 1, Occurrence = 1)
StrDeRef(String)
StrEndsWith(Haystack, Needle, CaseSensitive := false, Occurrence = 1)
StrStartsWith(Haystack, Needle, CaseSensitive := false, Occurrence = 1)
StrLower(ByRef InputVar, T = "")
StrUpper(ByRef InputVar, T = "")
StringCaseSense(OnOffLocale)
StringLower(ByRef InputVar, T = "")
StringUpper(ByRef InputVar, T = "")
Suspend(Mode = "")
SysGet(Subcommand, Param3 = "")
Thread(SubCommand, Value1 = "", Value2 = "")
Throw(Expression = "")
ToolTip(Text = "", X = "", Y = "", WhichToolTip = "")
TrayTip(Title = "", Text = "", Seconds = "", Options = "")
UrlDownloadToFile(URL, Filename)
WinActivate(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinActivateBottom(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGetActiveStats(ByRef Title, ByRef Width, ByRef Height, ByRef X, ByRef Y)
WinGetActiveTitle()
WinClose(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGet(SubCommand = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGetClass(OutputVar , WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGetID(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGetPos(ByRef X, ByRef Y, ByRef Width, ByRef Height, WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGetText(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinGetTitle(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinHide(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinKill(WinTitle = "", WinText = "", SecondsToWait = "", ExcludeTitle = "", ExcludeText = "")
WinMaximize(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinMenuSelectItem(WinTitle, WinText, Menu, SubMenu1 = "", SubMenu2 = "", SubMenu3 = "", SubMenu4 = "", SubMenu5 = "", SubMenu6 = "")
WinMinimize(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinMinimizeAll()
WinMinimizeAllUndo()
WinMove(WinTitle, WinText = "", X = "", Y = "", Width = "", Height = "", ExcludeTitle = "", ExcludeText = "")
WinRestore(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinSet(SubCommand, Value, WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinSetTitle(WinTitle, WinText = "", NewTitle = "", ExcludeTitle = "", ExcludeText = "")
WinShow(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
WinWait(WinTitle = "", WinText = "", TimeOut = "", ExcludeTitle = "", ExcludeText = "")
WinWaitActive(WinTitle = "", WinText = "", TimeOut = "", ExcludeTitle = "", ExcludeText = "")
WinWaitNotActive(WinTitle = "", WinText = "", TimeOut = "", ExcludeTitle = "", ExcludeText = "")
WinWaitClose(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
Gui(SubCommand = "New", Value1 = "", Value2 = "", Value3 = "")
