AutoTrim(Options = "")
BlockInput(Options = "")
Click(Options = "")
ClipWait(Timeout = "", WaitForAnyData = "")
Control(SubCommand = "" , Value = "", ControlHwnd = "")
ControlClick(ControlHwnd = "", WhichButton = "", ClickCount = "", Options = "")
ControlFocus(ControlHwnd = "")
ControlGetFocus(GuiHwnd = "")
ControlGetID(Control = "", GuiHwnd = "")
ControlGetPos(ByRef X, ByRef Y, ByRef Width, ByRef Height, ControlHwnd)
ControlGetText(ControlHwnd = "")
ControlMove(ControlHwnd, X = "", Y = "", Width = "", Height = "")
ControlSelect(ControlHwnd, GuiHwnd) ;WM_NEXTDLGCTL=0x0028
ControlSend(ControlHwnd = "", Keys = "")
ControlSendRaw(ControlHwnd = "", Keys = "")
ControlSetText(ControlHwnd = "", NewText = "")
CoordMode(TargetType, RelativeTo := "Screen")
Critical(OnOffNumeric = "On")
DetectHiddenText(OnOff)
DetectHiddenWindows(OnOff)
Drive(SubCommand = "", Value1 = "", Value2 = "")
DriveGet(Cmd, Value = "")
DriveSpaceFree(Path)
Edit()
EnvAdd(ByRef Var, Value = "" , TimeUnits = "")
EnvGet(EnvVarName)
EnvSet(EnvVar, Value)
EnvSub(ByRef Var, Value = "" , TimeUnits = "")
EnvUpdate()
FileAppend(Text = "", Filename = "", Encoding = "") ; FileAppend(Text, Filename) ; FileAppend("v=" v, Filename)
FileCopy(SourcePattern = "", DestPattern = "", Overwrite = "-Overwrite")
FileCopyDir(Source = "", Dest = "", Overwrite = "-Overwrite")
FileCreateDir(DirName = "")
FileCreateShortcut(Target, ByRef LinkFile, WorkingDir = "", Args = "", Description = "", IconFile = "", ShortcutKey = "", IconNumber = "", RunState = "")
FileDelete(FilePattern = "")
FileEncoding(Encoding = "")
FileGetAttrib(Filename = "")
FileGetShortcut(LinkFile, ByRef OutTarget = "", ByRef OutDir = "", ByRef OutArgs = "", ByRef OutDescription = "", ByRef OutIcon = "", ByRef OutIconNum = "", ByRef OutRunState = "")
FileGetSize(Filename = "", Units = "")
FileGetTime(Filename = "", WhichTime = "")
FileGetVersion(Filename = "")
FileInstall(Source, Dest, Overwrite = "")
FileMove(SourcePattern = "", DestPattern = "", Overwrite = "-Overwrite") ; FileMove(OldName, NewName, "Overwrite")
FileMoveDir(Source = "", ByRef Dest = "", Flag = "")
FileRead(Filename) ; options not supported
FileReadLine(Filename, LineNum)
FileRecycle(FilePattern = "")
FileRecycleEmpty(DriveLetter = "")
FileRemoveDir(DirName, Recurse = "")
FileRename(SourcePattern = "", DestPattern = "", Overwrite = "-Overwrite") ;Custom
FileSelectFile(Options = "", RootDir = "", Prompt = "", Filter = "")
FileSelectFolder(StartingFolder = "", Options = "", Prompt = "")
FileSetAttrib(Attributes = "", FilePattern = "", OperateOnFolders = "", Recurse = "")
FileSetTime(YYYYMMDDHH24MISS = "", FilePattern = "", WhichTime = "", OperateOnFolders = "", Recurse = "")
/**
Name:		FileWrite
About:	Writes text to a file with optional prompt to overwrite
In:			Text, Filename
Out:		None
*/
FileWrite(Text = "", Filename = "", Prompt = "-Prompt", Encoding = "") ;Custom
FormatTime(YYYYMMDDHH24MISS = "", Format = "") ; FormatTime(Now, "yyyy-MM-dd-hh:ss")
GroupActivate(GroupName, Mode = "")
GroupAdd(GroupName, HWND, Label = "")
GroupClose(GroupName, Mode = "")
GroupDeactivate(GroupName, Mode = "")
GuiControl(Subcommand = "", ControlHwnd = "", Value = "")
GuiControlGet(Subcommand = "", ControlID = "", Param4 = "")
IfBetween(ByRef var, LowerBound, UpperBound)
IfNotBetween_DEPRECIATED(ByRef var, LowerBound, UpperBound)
IfIn(ByRef var, MatchList)
IfNotIn_DEPRECIATED(ByRef var, MatchList)
IfContains(ByRef var, MatchList)
IfNotContains_DEPRECIATED(ByRef var, MatchList)
IfIs_DEPRECIATED(ByRef var, type)
IfIsNot_DEPRECIATED(ByRef var, type)
IfIs_Type(ByRef var, type)
ImageSearch(ByRef OutputVarX, ByRef OutputVarY, X1, Y1, X2, Y2, ImageFile)
IniDelete(Filename, Section, Key)
IniRead(Filename, Section, Key, Default = "")
IniWrite(ValueOrPairs, Filename, Section, Key="")
Input(Options = "", EndKeys = "", MatchList = "")
InputBox(Title = "", Prompt = "", HIDE = "", Width = "", Height = "", X = "", Y = "", Font = "", Timeout = "", Default = "")
IsType(ByRef var, type)
Join(Separator, params*) ; MsgBox % Join("`n", "one", "two", "three") ; MsgBox % Join("\", "C:", "Program Files", "Windows", "system", "my.exe")
JoinPath(Dir, File) ; MsgBox % JoinPath(A_ScriptDir, "Filename.exe")
KeyHistory()
KeyWait(KeyName, Options = "")
ListHotkeys()
ListLines(OnOff = "")
ListVars()
Menu(MenuName, SubCommand, Value1 = "", Value2 = "", Value3 = "", Value4 = "")
MouseClick(WhichButton = "", X = "", Y = "", ClickCount = "", Speed = "", DownOrUp = "", Relative = "")
MouseClickDrag(WhichButton, X1, Y1, X2, Y2, Speed = "", Relative = "")
MouseGetPos(ByRef OutputVarX = "", ByRef OutputVarY = "", ByRef OutputVarWin = "", ByRef OutputVarControl = "", Mode = "")
MouseMove(X, Y, Speed = "", Relative = "")
MB(Options = "", Title = "", Text = "", Timeout = "")
MsgBox(Options = "", Title = "", Text = "", Timeout = "")
OutputDebug(Text)
PixelGetColor(X, Y, RGB = "")
PixelSearch(ByRef OutputVarX, ByRef OutputVarY, X1, Y1, X2, Y2, ColorID, Variation = "", Mode = "")
PostMessage(Msg, wParam = "", lParam = "", ControlHwnd = "", HWND = "")
Process(SubCommand, PIDOrName = "", Value = "")
Random(Min = "", Max = "")
RegDelete(KeyName , ValueName = "")
RegRead(RootKey, SubKey, ValueName = "")
RegWrite(Valuetype = "", RootKey = "", SubKey = "", ValueName = "", Value = "")
Reload()
Run(Target = "", WorkingDir = "", Mode = "") ; Run("edit " TxtFile) ;notepad, Run(TxtFile) ;notepad++ if associated with .txt
RunAs(User = "", Password = "", Domain = "")
RunWait(Target, WorkingDir = "", Mode = "")
Send(Keys)
SendRaw(Keys)
SendInput(Keys)
SendPlay(Keys)
SendEvent(Keys)
SendLevel(Level)
SendMessage(Msg, wParam = "", lParam = "", ControlHwnd = "", HWND = "", Timeout = "")
SendMode(Mode)
SetBatchLines(Value)
SetCapsLockState(State)
SetControlDelay(Delay)
SetDefaultMouseSpeed(Speed)
SetKeyDelay(Delay = "", PressDuration = "", Play = "")
SetMouseDelay(Delay, Play = "")
SetNumLockState(State)
SetRegView(RegView)
SetScrollLockState(State)
SetStoreCapsLockMode(OnOff)
SetTimer(Label = "", PeriodOnOffDelete = "", Priority = "")
SetTitleMatchMode(Option = "")
SetWinDelayDelay(Delay)
SetWorkingDir(DirName)
Shutdown(Code)
Sleep(DelayInMilliseconds)
Sort(VarName, Options = "")
SoundBeep(Frequency = "", Duration = "")
SoundGet(ComponentType = "", ControlType = "", DeviceNumber = "")
SoundGetWaveVolume(DeviceNumber = "")
SoundPlay(Filename, Wait = "")
SoundSet(NewSetting, ComponentType = "", ControlType = "", DeviceNumber = "")
SoundSetWaveVolume(Percent , DeviceNumber = "")
SplitPath(ByRef InputVar, ByRef OutFileName = "", ByRef OutDir = "", ByRef OutExtension = "", ByRef OutNameNoExt = "", ByRef OutDrive = "")
SplitPathArray(InputVar = "") ; SplitPathArray(Filename).OutFilename
StatusBarGetText(Part = "", WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "")
StatusBarWait(BarText = "", Timeout = "", Part# = "", HWND = "")
StrBetween(Haystack = "", OpenNeedle = "", CloseNeedle = "", IncludeNeedles = False, CaseSensitive := False, OpenNeedleOccurrence = 1, CloseNeedleOccurrence = 1)
StrContains(Haystack, Needle, CaseSensitive = false, StartingPos = 1, Occurrence = 1)
StrEndsWith(Haystack, Needle, CaseSensitive := False, Occurrence = 1)
StrStartsWith(Haystack, Needle, CaseSensitive := False, Occurrence = 1)
StrIsBlank(Haystack)
StrIsEmpty(Haystack)
StrLower(ByRef InputVar, T = "")
StrUpper(ByRef InputVar, T = "")
StringCaseSense(OnOffLocale)
StringGetPos_DEPRECIATED(ByRef InputVar, SearchText, Mode = "", Offset = "")
StringLeft_DEPRECIATED(ByRef InputVar, Count)
StringLen_DEPRECIATED(ByRef InputVar)
StringLower(ByRef InputVar, T = "")
StringMid_DEPRECIATED(ByRef InputVar, StartChar, Count , L = "")
StringReplace_DEPRECIATED(ByRef InputVar, SearchText, ReplaceText = "", All = "")
StringRight_DEPRECIATED(ByRef InputVar, Count)
StringTrimLeft_DEPRECIATED(ByRef InputVar, Count)
StringTrimRight_DEPRECIATED(ByRef InputVar, Count)
StringUpper(ByRef InputVar, T = "")
Suspend(Mode = "")
SysGet(Subcommand, Param3 = "")
Thread(SubCommand, Value1 = "", Value2 = "")
Throw(Expression = "")
ToolTip(Text = "", X = "", Y = "", WhichToolTip = "")
TrayTip(Title = "", Text = "", Seconds = "", Options = "")
Transform_DEPRECIATED(Cmd, Value1, Value2 = "")
UrlDownloadToFile(URL, Filename)
WinActivate(HWND)
WinActivateBottom(HWND)
WinClose(HWND, SecondsToWait = "")
WinGet(SubCommand = "", HWND = "")
WinGetActiveStats(ByRef Title, ByRef Width, ByRef Height, ByRef X, ByRef Y)
WinGetActiveTitle()
WinGetClass(HWND)
WinGetID(WinTitle = "", WinText = "", ExcludeTitle = "", ExcludeText = "") ;from AHKv2, same as WinExist
WinGetPos(ByRef X, ByRef Y, ByRef Width, ByRef Height, GuiHwnd)
WinGetText(HWND)
WinGetTitle(HWND)
WinHide(HWND)
WinKill(HWND, SecondsToWait = "")
WinMaximize(HWND)
WinMenuSelectItem(HWND, Menu = "", SubMenu1 = "", SubMenu2 = "", SubMenu3 = "", SubMenu4 = "", SubMenu5 = "", SubMenu6 = "")
WinMinimize(HWND)
WinMinimizeAll()
WinMinimizeAllUndo()
WinMove(HWND = "", X = "", Y = "", Width = "", Height = "")
WinRestore(HWND)
WinSet(SubCommand = "" , Value = "", ControlHwnd = "")
WinSetTitle(GuiHwnd, NewTitle = "")
WinShow(HWND) ;WinShow(WinGetID(GuiTitle)
WinWait(HWND, Timeout = "") ;WinWait(WinGetID(GuiTitle), 5)
WinWaitActive(HWND, Timeout = "") ;WinWaitActive(WinGetID(GuiTitle), 5)
WinWaitNotActive(HWND, Timeout = "") ;WinWaitNotActive(WinGetID(GuiTitle), 5)
WinWaitClose(HWND)
